Acceptor Dynamic Session Templates
connamara/quickfixn pull request #607
Opened 2020-06-03 20:22 UTC by pavka1799

Enables "*" wildcard in Acceptor session configuration (for BeginString, SenderCompID, SenderSubID, SenderLocationID, TargetCompID, TargetSubID, and TargetLocationID).
Such session templates can be defined either at start-up or as an ad-hoc operation, just like "normal" sessions.
When processing a new incoming connection, if incoming SessionID is not equal to any of the created sessions, it is then matched considering wildcards. If such a match is found, the new session is created with the same settings as the template one, just changing wildcards to the actual values from incoming SessionID.

2020-06-10 17:39 UTC, gbirchmeier requested changes
Ok, first off, this is going to have some conflicts with #609.  That's not a big PR, but it does make a few changes to Session and SessionFactory.  I hope to merge #609 today.

I'm not crazy about the acceptor-specific additions to Session.  Can we think of any other approach?    Making a DynamicSession subclass seems possible off the top of my head, but also could be horrible.

Don't go deep into any big changes yet.  I also want to talk to @mgatny and see what ideas he has.

2020-06-16 15:54 UTC, gbirchmeier commented
FYI, #609 is in master now, so at your leisure you can upmerge or rebase.

2020-06-16 22:42 UTC, pavka1799 commented
I understood that I should wait for decision on architecture - is the
approach with passing acceptor into a session good enough? Or should it be
changed, probably by adding a class for "template" session?

On Tue, 16 Jun 2020, 17:54 Grant Birchmeier, <notifications@github.com>
wrote:

> FYI, #609 <https://github.com/connamara/quickfixn/pull/609> is in master
> now, so at your leisure you can upmerge or rebase.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/connamara/quickfixn/pull/607#issuecomment-644852954>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKABHZT5FA7TSPBMOK4MIE3RW6IU5ANCNFSM4NR74BKA>
> .
>

2020-06-17 13:36 UTC, gbirchmeier commented
Haven't had time to think about reworking the impl yet, but for now maybe just resolve the conflicts.

2020-06-17 22:52 UTC, pavka1799 commented
OK, will resolve

2020-06-18 21:34 UTC, pavka1799 commented
Conflicts resolved, and some of the suggested fixes made (marked them resolved). The rest will do after decision on the architecture.
Thank you!

2020-07-19 19:00 UTC, pavka1799 commented
@gbirchmeier  Apologies - have you had a chance to think about the architecture? I could do the changes if you have a better solution in mind.
Thank you!

2020-08-12 19:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/connamara/quickfixn?pullRequest=607) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/connamara/quickfixn?pullRequest=607) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: LittleAlexey<br/>:white_check_mark: gbirchmeier<br/>:white_check_mark: pavka1799<br/>:x: dependabot-preview[bot]<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/connamara/quickfixn?pullRequest=607) it.</sub>

2026-04-07 22:11 UTC, gbirchmeier commented
replaced by #650

2026-04-07 22:11 UTC, closed without merging